/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.util.*;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.*;
import java.awt.geom.Ellipse2D;
import java.awt.geom.*;
import javax.swing.JFrame;
public class Base extends javax.swing.JFrame {
    Graphics graphics;
    //private ArrayList<Shape> shape;
    private boolean red[];
    private ArrayList<Shape> node;
    private ArrayList<Shape> edge;
    private ArrayList<Shape> noontop;
    //private ArrayList<Shape> edgearrow; 
    private ArrayList<Integer> ed1,ed2;
    private boolean select=false;
    double x2,y2,h2,w2;
    double lx1,ly1,lx2,ly2;
    //int labelno=0;
    private ArrayList<Double> weight;
    
    
    
    public Base() {
        initComponents();
        node=new ArrayList<Shape>();
        edge=new ArrayList<Shape>();
        jButton1.setEnabled(false);
        ed1=new ArrayList<Integer>();
        ed2=new ArrayList<Integer>();    
        jButton2.setEnabled(false);
//setExtendedState(JFrame.MAXIMIZED_BOTH);
        System.out.println(jPanel1.getSize());
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jButton2 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<String>();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 830, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 471, Short.MAX_VALUE)
        );

        jToggleButton1.setText("node");

        jToggleButton2.setText("edge");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        jButton2.setText("MST");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setText("add Weight");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("done");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("clear");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(0, 204, 51));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("EDGES");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("MINIMUM SPANNING TREE");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel2))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBox1, 0, 97, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(157, 157, 157)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(52, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(349, 349, 349))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(jToggleButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jToggleButton2)
                .addGap(89, 89, 89)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(108, 108, 108))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton4)
                        .addComponent(jButton3)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        // TODO add your handling code here:
        int x=evt.getX();
        int y=evt.getY();
        if(jToggleButton1.isSelected()){
        graphics=jPanel1.getGraphics();
        Graphics2D g2d=(Graphics2D) graphics;
        g2d.setStroke(new BasicStroke(2));
        graphics.setColor(Color.black);
        Shape cir=new Ellipse2D.Double(x-20,y-20,40,40);
        g2d.draw(cir);
        node.add(cir);
        g2d.drawString(node.size()-1+"", x-2, y-24);
        System.out.println(node.size()-1);
        }
        if(jToggleButton2.isSelected()){
            Graphics2D g2d=(Graphics2D)graphics;
            g2d.setStroke(new BasicStroke(2));
            graphics.setColor(Color.red); 
            for(Shape n: node){
                Ellipse2D.Double l1=(Ellipse2D.Double) n;
                double x1=l1.getX();
                double y1=l1.getY();
                double w1=l1.getWidth();
                double h1=l1.getHeight();
                if(n.contains(evt.getPoint())){
                    if(!select){
                        select=true;
                        x2=x1;y2=y1;h2=h1;w2=w1;
                    Shape newcir=new Ellipse2D.Double(x1, y1, w1, h1);
                    System.out.println(node.indexOf(n));
                    node.set(node.indexOf(n),newcir);
                    g2d.draw(newcir);
                    ed1.add(node.indexOf(n));
                    }
                    else{
                        select=false;
                        Ellipse2D.Double l2=(Ellipse2D.Double) n;
                        double x3=l1.getX();
                        double y3=l1.getY();
                        System.out.println(node.indexOf(n));
                        graphics.setColor(Color.black);
                        Shape cir2=new Ellipse2D.Double(x2, y2, w2, h2);
                        g2d.draw(cir2);
                        //node.set(node.indexOf(n), cir2);
                        lx1=x2+20;
                        ly1=y2+20;
                        lx2=x3+20;
                        ly2=y3+20;
                        Shape line=new Line2D.Double(lx1, ly1, lx2, ly2);
                        //drawArrowLine(g2d,(int)lx1, (int)ly1, (int)lx2, (int)ly2,5,5);
                        
                        g2d.draw(line);
                        edge.add(line);
                        g2d.drawString(edge.size()+"", (int)((lx1+lx2)/2)+10, (int)((ly1+ly2)/2)-10);
                        jComboBox1.addItem("edge-"+edge.size());
                        ed2.add(node.indexOf(n));
                    }                    
                }
            }
        }
    }//GEN-LAST:event_jPanel1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        EdgeWeightedGraph g=new EdgeWeightedGraph(node.size());
        for(int i=0;i<edge.size();i++){
            Edge e=new Edge(ed1.get(i),ed2.get(i),weight.get(i));
            g.addEdge(e);
        }       
        System.out.println(g.toString());
        Eager_Prim ep=new Eager_Prim(g);
        System.out.println(ep.edges());
        graphics.setColor(Color.red);
        Graphics2D g2d=(Graphics2D) graphics;
        g2d.setStroke(new BasicStroke(2));
        jLabel4.setText("Minimum weight= "+ep.weight());
        for(Edge e: ep.edges()){
            for(int i=0;i<edge.size();i++){
                if(e.first()==ed1.get(i)&& e.second()==ed2.get(i)){
                    g2d.draw(edge.get(i));
                    red[i]=true;
                    System.out.println(e);
                    System.out.println(ed1.get(i)+"---"+ed2.get(i));
                }
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int index=jComboBox1.getSelectedIndex();
        Double data=Double.parseDouble(jTextField1.getText());
        weight.set(index,data);
        System.out.println("-"+data);
        System.out.println(weight);
        jLabel1.setText("edge-"+(index+1)+" weight is added");
        //.setText("edge-"+labelno);
        //labelno++;
    }//GEN-LAST:event_jButton1ActionPerformed

    @Override
    public void paint(Graphics g){
        super.paint(g);
        g=jPanel1.getGraphics();
        Graphics2D g2d=(Graphics2D)g;
        g2d.setStroke(new BasicStroke(2));
        for(int i=0;i<node.size();i++){
            Ellipse2D.Double l1=(Ellipse2D.Double) node.get(i);
            double x=l1.getX()+20;
            double y=l1.getY()+20;
            g2d.draw(node.get(i));
            g2d.drawString(i+"", (int)x-2, (int)y-24);
            //g2d.draw(edge.get(i));
        }
        for(Shape e:edge){
            if(red[edge.indexOf(e)]){
                g2d.setColor(Color.red);
                g2d.draw(e);
            }
            else{
                g2d.setColor(Color.black);
                g2d.draw(e);
            }
            Line2D.Double l1=(Line2D.Double) e;
            double xx1=l1.x1;
            double xx2=l1.x2;
            double yy1=l1.y1;
            double yy2=l1.y2;
            g2d.drawString(edge.size()+"", (int)((xx1+xx2)/2)+10, (int)((yy1+yy2)/2)-10);
        }
    }
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int max=jComboBox1.getComponentCount();
        weight=new ArrayList<Double>(edge.size());
        for(int i=0;i<edge.size();i++)
            weight.add(1.0);
        System.out.println("------"+max+"---"+edge.size());
        jButton1.setEnabled(true);
        jToggleButton1.setEnabled(false);
        jToggleButton2.setEnabled(false);
        jButton3.setEnabled(false);
        jButton2.setEnabled(true);
        red=new boolean[edge.size()];
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        jButton1.setEnabled(false);
        jToggleButton1.setEnabled(true);
        jToggleButton2.setEnabled(true);
        jComboBox1.removeAllItems();
        jTextField1.setText("");
        jPanel1.repaint();
        node=new ArrayList<Shape>();
        edge=new ArrayList<Shape>();
        jButton3.setEnabled(true);
        jLabel1.setText("");
        ed1=new ArrayList<Integer>();
        ed2=new ArrayList<Integer>();
        weight=new ArrayList<Double>();
        //eight=new ArrayList<Double>();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton2ActionPerformed
/*private void drawArrowLine(Graphics g, int x1, int y1, int x2, int y2, int d, int h) {
    int dx = x2 - x1, dy = y2 - y1;
    double D = Math.sqrt(dx*dx + dy*dy);
    double xm = D - d, xn = xm, ym = h, yn = -h, x;
    double sin = dy / D, cos = dx / D;

    x = xm*cos - ym*sin + x1;
    ym = xm*sin + ym*cos + y1;
    xm = x;

    x = xn*cos - yn*sin + x1;
    yn = xn*sin + yn*cos + y1;
    xn = x;

    int[] xpoints = {x2, (int) xm, (int) xn};
    int[] ypoints = {y2, (int) ym, (int) yn};

    g.drawLine(x1, y1, x2, y2);
    g.fillPolygon(xpoints, ypoints, 3);
}*/
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Base.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Base.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Base.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Base.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Base().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    // End of variables declaration//GEN-END:variables
}


//graph (impl)
//weighted graph (impl)
//spanning tree
//minimum spanning tree
//algorithm to find minimum spanning tree
//Prims algo. and Kruskal algo.